openapi: 3.0.3
info:
  title: ACI Alerts API
  description: Alert management endpoints for Armor Cyber Intelligence
  version: 1.0.0

paths:
  /v1/alerts:
    get:
      summary: List user alerts
      operationId: listAlerts
      tags:
        - Alerts
      security:
        - bearerAuth: []
      parameters:
        - name: active_only
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Alert'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create alert
      operationId: createAlert
      tags:
        - Alerts
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlertRequest'
      responses:
        '201':
          description: Alert created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Alert already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/alerts/{id}:
    get:
      summary: Get alert by ID
      operationId: getAlert
      tags:
        - Alerts
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Alert details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update alert
      operationId: updateAlert
      tags:
        - Alerts
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlertRequest'
      responses:
        '200':
          description: Alert updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete alert
      operationId: deleteAlert
      tags:
        - Alerts
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Alert deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Alert deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/alerts/{id}/matches:
    get:
      summary: Get alert matches
      operationId: getAlertMatches
      tags:
        - Alerts
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: since
          in: query
          schema:
            type: string
            format: date-time
          description: Only matches after this timestamp
      responses:
        '200':
          description: Alert matches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertMatchesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/stats/dashboard:
    get:
      summary: Get dashboard statistics
      operationId: getDashboardStats
      tags:
        - Statistics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardStats'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/stats/categories:
    get:
      summary: Get category statistics
      operationId: getCategoryStats
      tags:
        - Statistics
      security:
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          schema:
            type: string
            enum: [day, week, month]
            default: week
      responses:
        '200':
          description: Category statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryStats'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/stats/trends:
    get:
      summary: Get trend statistics
      operationId: getTrendStats
      tags:
        - Statistics
      security:
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          schema:
            type: string
            enum: [day, week, month]
            default: week
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 30
            default: 7
      responses:
        '200':
          description: Trend statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrendStats'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    AlertType:
      type: string
      enum: [keyword, category, severity, vendor, cve]

    AlertPriority:
      type: string
      enum: [critical, high, normal]

    Alert:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: VMware Vulnerabilities
        type:
          $ref: '#/components/schemas/AlertType'
        value:
          type: string
          example: vmware
        is_active:
          type: boolean
        match_count:
          type: integer
          description: Total matches
        last_match_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateAlertRequest:
      type: object
      required:
        - name
        - type
        - value
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: VMware Vulnerabilities
        type:
          $ref: '#/components/schemas/AlertType'
        value:
          type: string
          minLength: 1
          maxLength: 500
          example: vmware
          description: |
            Value interpretation depends on type:
            - keyword: search term
            - category: category slug
            - severity: critical/high/medium/low
            - vendor: vendor name
            - cve: CVE ID pattern (e.g., CVE-2024-*)

    UpdateAlertRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        value:
          type: string
          minLength: 1
          maxLength: 500
        is_active:
          type: boolean

    AlertMatch:
      type: object
      properties:
        id:
          type: string
          format: uuid
        alert:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            type:
              $ref: '#/components/schemas/AlertType'
        article:
          type: object
          properties:
            id:
              type: string
              format: uuid
            title:
              type: string
            slug:
              type: string
            severity:
              type: string
            category_slug:
              type: string
            published_at:
              type: string
              format: date-time
        priority:
          $ref: '#/components/schemas/AlertPriority'
        matched_at:
          type: string
          format: date-time
        notified_at:
          type: string
          format: date-time

    AlertMatchesResponse:
      type: object
      properties:
        matches:
          type: array
          items:
            $ref: '#/components/schemas/AlertMatch'
        pagination:
          $ref: '#/components/schemas/Pagination'

    DashboardStats:
      type: object
      properties:
        today:
          type: object
          properties:
            total_articles:
              type: integer
            critical_articles:
              type: integer
            high_articles:
              type: integer
            alert_matches:
              type: integer
        week:
          type: object
          properties:
            total_articles:
              type: integer
            critical_articles:
              type: integer
            high_articles:
              type: integer
            alert_matches:
              type: integer
        user:
          type: object
          properties:
            active_alerts:
              type: integer
            bookmarks:
              type: integer
            unread_matches:
              type: integer

    CategoryStats:
      type: object
      properties:
        period:
          type: string
          enum: [day, week, month]
        categories:
          type: array
          items:
            type: object
            properties:
              slug:
                type: string
              name:
                type: string
              color:
                type: string
              article_count:
                type: integer
              percentage:
                type: number
                format: float

    TrendStats:
      type: object
      properties:
        period:
          type: string
          enum: [day, week, month]
        data:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              total_articles:
                type: integer
              critical_articles:
                type: integer
              high_articles:
                type: integer
              by_category:
                type: object
                additionalProperties:
                  type: integer

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total_items:
          type: integer
        total_pages:
          type: integer
        has_next:
          type: boolean
        has_prev:
          type: boolean

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
            request_id:
              type: string
              format: uuid
